# Use a imagem oficial do OpenJDK como base
FROM openjdk:11-jre-slim

# Define o diretório de trabalho
WORKDIR /app

# Copie o JAR da sua aplicação para o container
COPY target/minha-aplicacao.jar /app/minha-aplicacao.jar

# Exponha a porta que a aplicação irá usar
EXPOSE 8080

# Comando para rodar a aplicação
CMD ["java", "-jar", "minha-aplicacao.jar"]
